# Generated by Django 4.2.2 on 2023-10-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_recipient_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
