# Generated by Django 4.2.2 on 2023-10-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
